title: <p align="center"> Arif Zafri </p>

#logo: "https://github.com/arifzafri106/arifzafri106.github.io/blob/master/images/84439768.jpeg"

description:
  <p align="center">
  <a href="https://github.com/arifzafri106/arifzafri106.github.io/blob/master/pdf/Mohd%20Arif%20Zafri%20Mohd%20Mokhtar%20Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/m-arifzafri/">LinkedIn</a> |
  <a href="https://github.com/arifzafri106">GitHub</a> |
  <a href="https://public.tableau.com/app/profile/arif.zafri">Tableau</a>  
  </p>
  
  <p align="justify">
  Graduated with a Mechanical Engineering Bachelor's Degree in 2019. Worked as a Mechanical Engineer for nearly 2 years and decided to pursue a career change in Data Analytics
  Email; m.arifzafri@gmail.com
  <br><br>
  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
